<a href="https://colab.research.google.com/github/carloscase66-cyber/fluffy-fishstick/blob/main/Projeto_mod_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import pandas as pd

df = pd.read_csv("adult11.csv")
df.info()
df.describe(include="all")
df.isnull().sum()
df.nunique()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             48842 non-null  int64
 1   workclass       48842 non-null  object
 2   fnlwgt          48842 non-null  int64
 3   education       48842 non-null  object
 4   education-num   48842 non-null  int64
 5   marital-status  48842 non-null  object
 6   occupation      48842 non-null  object
 7   relationship    48842 non-null  object
 8   race            48842 non-null  object
 9   gender          48842 non-null  object
 10  capital-gain    48842 non-null  int64
 11  capital-loss    48842 non-null  int64
 12  hours-per-week  48842 non-null  int64
 13  native-country  48842 non-null  object
 14  salary          48842 non-null  object
dtypes: int64(6), object(9)
memory usage: 5.6+ MB

age                  74
workclass             9
fnlwgt            28523
education            16
education-num        16
marital-status        7
occupation           15
relationship          6
race                  5
gender                2
capital-gain        123
capital-loss         99
hours-per-week       96
native-country       42
salary                2
dtype: int64

In [14]:
df = df.loc[:, df.nunique() > 1]
df = df.dropna()
df = df.map(lambda x : x.strip().lower() if isinstance(x, str) else x)
for col in df.select_dtypes(include="object").columns:
  df[col] = df[col].astype("category")

In [15]:
df['salary'].value_counts()
df['gender'].value_counts(normalize=True)
df[df['salary'] == '>50k']['age'].mean()
df['occupation'].value_counts().head(10)
df.groupby('education')['salary'].value_counts(normalize=True)
df.groupby('salary')['hours-per-week'].mean()
df[df['salary'] == '>50k']['native-country'].value_counts(normalize=True).head(10)
df.groupby('salary')['age'].describe()
df.groupby('gender')['salary'].value_counts(normalize=True)
df[['age', 'hours-per-week']].corr()

/tmp/ipykernel_474/3713154128.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('education')['salary'].value_counts(normalize=True)
/tmp/ipykernel_474/3713154128.py:6: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('salary')['hours-per-week'].mean()
/tmp/ipykernel_474/3713154128.py:8: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('salary')['age'].describe()
/tmp/ipykernel_474/3713154128.py:9: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('gender')['salary'].value_counts(normalize=True)

                     age  hours-per-week
age             1.000000        0.071558
hours-per-week  0.071558        1.000000